# a workflow runs on release, sets up deno, then runs deno-build.ts, then uploads dist/build/* to release assets
name: Release on tags push
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install --entrypoint cli.ts
      - run: deno run -A deno-build.ts exe ${{ github.ref }}
      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: "dist/build/*.zip"
          allowUpdates: true
          omitBody: true